### ISSUE TITLE
Uninstall procedure

### ISSUE THREAD

**Issue by ensadeq** [ScriptNinja-GNU/YggdraSpeed-Mesh-Weaver#1]
How can I delete all settings that were configured by the script?

**Comment by z2ray** [comment]
pls explain how to remove core, config and all of script junk file?

**Comment by hamedp6** [comment]
this script does not have any uninstallation procedure, how do we uninstall it?

**Comment by ScriptNinja-GNU** [comment]
First, stop the project, then delete the entire directory

sudo systemctl stop yggdrasil
sudo systemctl disable yggdrasil
